name       : hunspell-da
version    : 2.4
release    : 2
source     :
    - https://extensions.libreoffice.org/assets/downloads/z/dict-da-2-4.oxt : c08a7c53dcbae49f5ebb3274e673ec983f623f52c9f8d6f471887de7e4a62476
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : office.spelling
extract    : no
summary    : Danish hunspell dictionary
description: |
    Danish dictionary from Stavekontrolden / Danske ordbog til stavekontrol fra Stavekontrolden.
setup      : |
    unzip $sources/dict-da-2-4.oxt
install    : |
    install -Dm00644 da_DK.{aff,dic} -t $installdir/usr/share/hunspell
